### ISSUE TITLE
Not working on Big Sur.

### ISSUE THREAD

**Issue by ghost** [chris1111/AtherosL1cEthernet#2]
Hello friend how are you? This kext not working for me on Big Sur. Thanks.

**Comment by chris1111** [comment]
Good You ?
Ok thanks to report

**Comment by ghost** [comment]
Hello, it's me again. As I said earlier, when using Kext on both Catalina and Big Sur, the system does not start my system. I believe it is some kind of incompatibility with my hardware. Follow it below as well as the log of my PCs:


SPECS:

    Mobo: Positivo POS-EIH61CE
    Chipset: Intel Cougar Point H61 (Ivy Bridge)
    CPU: i5-3570k
    LAN: Qualcomm Atheros AR8152 PCI-E Fast Ethernet Controller 

[
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x0,0x0)",
    "DeviceName" : "Xeon E3-1200 v2\/3rd Gen Core processor DRAM Controller",
    "ShadowDevice" : 336,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/pci8086,150@0",
    "SlotName" : "Internal@0,0,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,150",
    "ClassCode" : 393216,
    "Address" : 0,
    "PCIDebug" : "00:00.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Bridge",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/pci8086,150@0",
    "Model" : "???",
    "SubClassName" : "Host bridge",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 336,
    "BundleID" : "com.apple.driver.AppleACPIPlatform"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x2,0x0)",
    "DeviceName" : "Intel Xeon E3-1200 v2\/3rd Gen Core processor Graphics Controller",
    "ShadowDevice" : 354,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/GFX0@2",
    "SlotName" : "Internal@0,2,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "display",
    "ClassCode" : 196608,
    "Address" : 131072,
    "PCIDebug" : "00:02.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Display controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/GFX0@2",
    "Model" : "???",
    "SubClassName" : "VGA compatible controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 354,
    "BundleID" : "com.apple.iokit.IONDRVSupport"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1B,0x0)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family High Definition Audio Controller",
    "ShadowDevice" : 7200,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/HDEF@1B",
    "SlotName" : "Internal@0,27,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c20",
    "ClassCode" : 262912,
    "Address" : 1769472,
    "PCIDebug" : "00:1B.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Multimedia controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/HDEF@1B",
    "Model" : "???",
    "SubClassName" : "Audio device",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7200,
    "BundleID" : "com.apple.driver.AppleHDAController"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x16,0x0)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family MEI Controller #1",
    "ShadowDevice" : 7226,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/pci8086,1c3a@16",
    "SlotName" : "Internal@0,22,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c3a",
    "ClassCode" : 491520,
    "Address" : 1441792,
    "PCIDebug" : "00:16.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Communication controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/pci8086,1c3a@16",
    "Model" : "???",
    "SubClassName" : "Communication controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7226,
    "BundleID" : "com.apple.driver.AppleACPIPlatform"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1C,0x0)",
    "DeviceName" : "82801 PCI Bridge",
    "ShadowDevice" : 9294,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/RP01@1C",
    "SlotName" : "Internal@0,28,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci-bridge",
    "ClassCode" : 394241,
    "Address" : 1835008,
    "PCIDebug" : "00:1C.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Bridge",
    "SubDeviceID" : 0,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/RP01@1C",
    "Model" : "???",
    "SubClassName" : "PCI bridge",
    "SubVendorID" : 0,
    "ShadowVendor" : 32902,
    "DeviceID" : 9294,
    "BundleID" : "com.apple.iokit.IOPCIFamily"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1A,0x0)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family USB Enhanced Host Controller #2",
    "ShadowDevice" : 7213,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/EHC2@1A",
    "SlotName" : "Internal@0,26,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c2d",
    "ClassCode" : 787232,
    "Address" : 1703936,
    "PCIDebug" : "00:1A.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Serial bus controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/EHC2@1A",
    "Model" : "???",
    "SubClassName" : "USB controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7213,
    "BundleID" : "com.apple.driver.usb.AppleUSBEHCIPCI"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1C,0x4)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family PCI Express Root Port 5",
    "ShadowDevice" : 7192,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/RP05@1C,4",
    "SlotName" : "Internal@0,28,4",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci-bridge",
    "ClassCode" : 394240,
    "Address" : 1835012,
    "PCIDebug" : "00:1C.4",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Bridge",
    "SubDeviceID" : 0,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/RP05@1C,4",
    "Model" : "???",
    "SubClassName" : "PCI bridge",
    "SubVendorID" : 0,
    "ShadowVendor" : 32902,
    "DeviceID" : 7192,
    "BundleID" : "com.apple.iokit.IOPCIFamily"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1F,0x0)",
    "DeviceName" : "H61 Express Chipset LPC Controller",
    "ShadowDevice" : 7260,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/LPCB@1F",
    "SlotName" : "Internal@0,31,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c5c",
    "ClassCode" : 393472,
    "Address" : 2031616,
    "PCIDebug" : "00:1F.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Bridge",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/LPCB@1F",
    "Model" : "???",
    "SubClassName" : "ISA bridge",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7260,
    "BundleID" : "com.apple.driver.AppleLPC"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1D,0x0)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family USB Enhanced Host Controller #1",
    "ShadowDevice" : 7206,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/EHC1@1D",
    "SlotName" : "Internal@0,29,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c26",
    "ClassCode" : 787232,
    "Address" : 1900544,
    "PCIDebug" : "00:1D.0",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Serial bus controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/EHC1@1D",
    "Model" : "???",
    "SubClassName" : "USB controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7206,
    "BundleID" : "com.apple.driver.usb.AppleUSBEHCIPCI"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1F,0x2)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller",
    "ShadowDevice" : 7170,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/SAT0@1F,2",
    "SlotName" : "Internal@0,31,2",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c02",
    "ClassCode" : 67073,
    "Address" : 2031618,
    "PCIDebug" : "00:1F.2",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Mass storage controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/SAT0@1F,2",
    "Model" : "???",
    "SubClassName" : "SATA controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7170,
    "BundleID" : "com.apple.driver.AppleAHCIPort"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1F,0x3)",
    "DeviceName" : "6 Series\/C200 Series Chipset Family SMBus Controller",
    "ShadowDevice" : 7202,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/SBUS@1F,3",
    "SlotName" : "Internal@0,31,3",
    "ASPM" : "Disabled",
    "IORegIOName" : "pci8086,1c22",
    "ClassCode" : 787712,
    "Address" : 2031619,
    "PCIDebug" : "00:1F.3",
    "VendorName" : "Intel Corporation",
    "ClassName" : "Serial bus controller",
    "SubDeviceID" : 12688,
    "VendorID" : 32902,
    "IORegName" : "\/PCI0@0\/SBUS@1F,3",
    "Model" : "???",
    "SubClassName" : "SMBus",
    "SubVendorID" : 4121,
    "ShadowVendor" : 32902,
    "DeviceID" : 7202,
    "BundleID" : "com.apple.driver.AppleACPIPlatform"
  },
  {
    "DevicePath" : "PciRoot(0x0)\/Pci(0x1C,0x4)\/Pci(0x0,0x0)",
    "DeviceName" : "AR8152 v2.0 Fast Ethernet",
    "ShadowDevice" : 8290,
    "IORegPath" : "IOService:\/AppleACPIPlatformExpert\/PCI0@0\/AppleACPIPCI\/RP05@1C,4\/IOPP\/PXSX@0",
    "SlotName" : "Internal@0,28,4\/0,0",
    "ASPM" : "Disabled",
    "IORegIOName" : "ethernet",
    "ClassCode" : 131072,
    "Address" : 0,
    "PCIDebug" : "02:00.0",
    "VendorName" : "Qualcomm Atheros",
    "ClassName" : "Network controller",
    "SubDeviceID" : 33106,
    "VendorID" : 6505,
    "IORegName" : "\/PCI0@0\/RP05@1C,4\/PXSX@0",
    "Model" : "???",
    "SubClassName" : "Ethernet controller",
    "SubVendorID" : 4121,
    "ShadowVendor" : 6505,
    "DeviceID" : 8290,
    "BundleID" : "com.apple.iokit.IOPCIFamily"
  }
]
